apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ntnh1wl2s-python
  janus-idp.io/tekton: ntnh1wl2s-python
  backstage.io/kubernetes-id: ntnh1wl2s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ntnh1wl2s-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
